
source 'https://github.com/CocoaPods/Specs.git'

# 对于Swift应用来说下面两句是必须的
platform :ios, '8.0'
use_frameworks!

target "TianJiCloud" do
  
# Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React',
     :path => '../node_modules/react-native', 
     :subspecs => [
       'Core',
       'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
       'RCTText',
       'RCTNetwork',
       'RCTWebSocket', # needed for debugging
       'BatchedBridge',
            
       # Add any other subspecs you want to use in your project

      
  
]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'


    pod 'YTKNetwork', '~> 2.0.3'
    pod 'YTKKeyValueStore'
    pod 'GTSDK', '1.6.2.0-noidfa'
    pod 'AlipaySDK-2.0'
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/Sina'
    pod 'UMengUShare/Social/WeChat'
    pod 'UMengUShare/Social/QQ'
    pod 'LKDBHelper'
    pod 'YYModel'
    pod 'YYCategories'
    pod 'BlocksKit/UIKit', '~> 2.2.5'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'SDCycleScrollView', '~> 1.64'
    pod 'DACircularProgress'
    pod 'DZNEmptyDataSet'
    pod 'WZLBadge'
    pod 'TZImagePickerController'
    pod 'ZFPlayer'    
    pod 'IQKeyboardManager'
    
    inhibit_all_warnings!
end




